// <auto-generated />
namespace Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addedresetfrommail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedresetfrommail));
        
        string IMigrationMetadata.Id
        {
            get { return "202301091801467_Added reset from mail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
